# Courtesy of Maarten Tibau (https://maarten.be/blog/20220730/how-to-deploy-your-eleventy-website-to-github-pages-with-github-actions/)
name: Build on PR

on:
  pull_request:
    branches: ['gh_pages']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.17.6']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version  }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version  }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build
