name: Eleventy Build

on:
  push:
    branches:
      - gh_pages
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '10.x'

        - run: npm ci

        - run: npm run build

        - name: Deploy
          uses: zfriedman0/homepage@v1
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
